theme: jekyll-theme-leap-day
title: Never Stop Developing
description: Personal developer blog for Cyburstud - Bradley Anderson
author: Bradley Anderson
email: cyburstud@gmail.com
permalink: /:categories/:year/:month/:day/:title:output_ext
include:
  - LOL
  - _posts

# social links
twitter_username: cyburstud # DO NOT include the @ character, or else the build will fail!
github_username:  cyburstud # DO NOT include the @ character, or else the build will fail!
linkedin_username: bradley-anderson-03558382

show_excerpts: true # set to false to remove excerpts on the homepage
