theme: jekyll-theme-leap-day
title: Never Stop Developing
description: Personal developer blog for Cyburstud - Bradley Anderson
author: Bradley Anderson
email: cyburstud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The github profile page for Cyburstud. Mainly reflecting and referencing current public projects in the works of development, references to information or material he wants to share as well as quirky coding. 

# social links
twitter_username: cyburstud # DO NOT include the @ character, or else the build will fail!
github_username:  cyburstud # DO NOT include the @ character, or else the build will fail!
linkedin_username: bradley-anderson-03558382

show_excerpts: true # set to false to remove excerpts on the homepage
